#########################################################################
# Title:         Saltbox: btop | Default Variables                      #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
btop_releases_url: "https://api.github.com/repos/aristocratos/btop/releases/latest"

btop_releases_download_url: https://github.com/aristocratos/btop/releases/download

btop_version_lock: false
btop_version_lock_url: "https://github.com/aristocratos/btop/releases/download/v1.4.6/btop-{{ 'aarch64' if ansible_facts['architecture'] in ['aarch64', 'arm64'] else 'x86_64' }}-unknown-linux-musl.tbz"
